# SPDX-License-Identifier: BSD-3-Clause
"""Calculate random displacements from phonons at finite temperatures."""

from __future__ import annotations

import warnings
from typing import Literal

import numpy as np
from numpy.typing import NDArray

from phonopy.harmonic.dynamical_matrix import get_dynamical_matrix
from phonopy.harmonic.dynmat_to_fc import (
    DynmatToForceConstants,
    categorize_commensurate_points,
    get_commensurate_points_in_integers,
)
from phonopy.physical_units import get_physical_units
from phonopy.structure.atoms import PhonopyAtoms
from phonopy.structure.cells import Primitive


def bose_einstein_dist(
    x: NDArray[np.double] | float, t: float
) -> NDArray[np.double] | float:
    """Return Bose-Einstein distribution.

    Parameters
    ----------
    x : ndarray or float
        Phonon frequencies in THz.
    t : float
        Temperature in K.

    Returns
    -------
    ndarray or float
        Phonon occupation numbers.

    """
    return 1.0 / (
        np.exp(get_physical_units().THzToEv * x / (get_physical_units().KB * t)) - 1
    )


class RandomDisplacements:
    """Generate random displacements by Canonical ensenmble.

    Note
    ----
    Phonon frequencies are used to calculate phonon occupation number,
    for which phonon frequencies have to be given in THz. Therefore unit
    conversion factor has to be specified at the initialization.

    Imaginary phonon modes are treated so as to have their absolute phonon
    frequencies |omega| and phonon modes having |omega| < cutoff_frequency
    are ignored.

    Attributes
    ----------
    u : ndarray
        Random atomic displacements generated by canonical distribution of
        harmonic oscillator. The unit of distance is Angstrom.
        shape=(number_of_snapshots, supercell_atoms, 3)
        dtype='double', order='C'
    qpoints : ndarray
        Commensurate q-points corresponding to the supercell matrix but not
        all. Only half of the commensurate q-points that are not on the BZ
        boundary and Gamma-points are only taken, because of the symmetry
        of dynamical matrix: omega_q = omega_-q and e_q = e_-q^*.
    frequencies : ndarray
        Phonon frequencies at commensurate q-points as explained above
        qpoints attribute. Both of getter and setter are implemented.
        The aim of this is to modify random displacements by modifying
        frequencies by users. The unit is in THz.
        shape=(len(qpoints), num_band), dtype='double', order='C'
        where num_band is 3 * number of atoms in primitive cell.
    force_constants : ndarray
        Force constants calculated from phonon frequencies and eigenvectors
        at commensurate q-points as given above qpoints attribute. By this,
        phonon can be calculated with modified phonon frequencies. To
        calculate force constants, run_d2f has to be executed. For example,

            rd = RandomDisplacements(supercell, primitive, force_constants)
            freqs = rd.frequencies
            ... modify freqs by users
            rd.frequencies = freqs
            rd.run(500)  # To get random displacements
            rd.run_d2f()
            fc = rd.force_constants  # To draw phonons with modified freqs

        shape=(superell_atoms, supercell_atoms, 3, 3)
        dtype='double', order='C'

    """

    def __init__(
        self,
        supercell: PhonopyAtoms,
        primitive: Primitive,
        force_constants: NDArray[np.double],
        dist_func: Literal["quantum", "classical"] | None = None,
        cutoff_frequency: float | None = None,
        max_distance: float | None = None,
        factor: float | None = None,
        use_openmp: bool = False,
        sampling_matrix: Literal["symmetric", "eigenvector"] | None = None,
    ):
        """Init method.

        Parameters
        ----------
        supercell : PhonopyAtoms
            Supercell.
        primitive : Primitive
            Primitive cell
        force_constants : array_like
            Force constants matrix. See the details at docstring of
            DynamialMatrix.
        dist_func : str or None
            Harmonic oscillator distribution function either by 'quantum'
            or 'classical'. The starndard deviation of normal distribution
            is determined following the choice. Default is None, corresponding
            to 'quantum'.
        cutoff_frequency : float
            Lowest phonon frequency below which frequency the phonon mode
            is treated specially. See _get_sigma. Default is None, which
            means 0.01.
        max_distance : float or None, optional
            In random displacements generation from canonical ensemble of
            harmonic phonons, displacements larger than max distance are
            renormalized to the max distance, i.e., a disptalcement d is shorten
            by d -> d / |d| * max_distance if |d| > max_distance.
        factor : float
            Phonon frequency unit conversion factor to THz
        use_openmp : bool, optional, default=False
            Use OpenMP in calculate dynamical matrix and its inverse.
        sampling_matrix : str or None, optional
            How the random normals are turned into displacements. Both
            choices give the same distribution, but the same random numbers
            give different displacements. Default is None, i.e. 'symmetric'.

            'symmetric'
                Use the Hermitian square root, E.diag(sigma).E^dagger, per
                commensurate q. This depends on the force constants alone,
                so a fixed random seed gives the same displacements whatever
                eigenvectors the eigensolver returns, and nearby force
                constants give nearby displacements.
            'eigenvector'
                Use E.diag(sigma), the behaviour of phonopy 4.4 and earlier.

        """
        if cutoff_frequency is None or cutoff_frequency < 0:
            self._cutoff_frequency = 0.01
        else:
            self._cutoff_frequency = cutoff_frequency
        self._max_distance = max_distance

        _physical_units = get_physical_units()
        if factor is None:
            self._factor = _physical_units.DefaultToTHz
        else:
            self._factor = factor
        self._T: float | None = None
        self._u: NDArray[np.double] | None = None

        if dist_func is None or dist_func == "quantum":
            self._dist_func = "quantum"
        elif dist_func == "classical":
            self._dist_func = "classical"
        else:
            raise RuntimeError("Either 'quantum' or 'classical' is required.")

        if sampling_matrix is None:
            self._sampling_matrix = "symmetric"
        elif sampling_matrix in ("symmetric", "eigenvector"):
            self._sampling_matrix = sampling_matrix
        else:
            raise RuntimeError("Either 'symmetric' or 'eigenvector' is required.")

        self._unit_conversion = (
            _physical_units.Hbar
            * _physical_units.EV
            / _physical_units.AMU
            / _physical_units.THz
            / (2 * np.pi)
            / _physical_units.Angstrom**2
        )
        self._unit_conversion_classical = (
            _physical_units.KB
            * _physical_units.EV
            / _physical_units.AMU
            / (_physical_units.THz * (2 * np.pi)) ** 2
            / _physical_units.Angstrom**2
        )

        # Dynamical matrix without NAC because of commensurate points only
        self._dynmat = get_dynamical_matrix(
            force_constants, supercell, primitive, use_openmp=use_openmp
        )

        self._comm_points: NDArray[np.int64]
        self._ii: list[int]
        self._ij: list[int]
        self._setup_sampling_qpoints(supercell.cell, primitive.cell)

        self._n_patom = len(primitive)
        self._n_lattice = len(supercell) // self._n_patom
        # Positions and phases are ordered (primitive atom, lattice point) so
        # that _solve_ii and _solve_ij accumulate efficiently; _to_supercell
        # returns the displacements they generate to the supercell order.
        p2p = primitive.p2p_map
        self._ppl2s = np.argsort([p2p[i] for i in primitive.s2p_map], kind="stable")
        self._s2ppl = np.empty(len(supercell), dtype=int)
        self._s2ppl[self._ppl2s] = np.arange(len(supercell))
        self._ppos = primitive.scaled_positions

        self._eigvals_ii: NDArray[np.double]
        self._eigvecs_ii: NDArray[np.double]
        self._phase_ii: NDArray[np.double]
        self._eigvals_ij: NDArray[np.double]
        self._eigvecs_ij: NDArray[np.cdouble]
        self._phase_ij: NDArray[np.cdouble]
        self._prepare()

        # This is set when running run_d2f.
        # The aim is to produce force constants from modified frequencies.
        self._force_constants: NDArray[np.double] | None = None

        # Displacement correlation matrix (nsatom, nsatom, 3, 3)
        self._uu: NDArray[np.double] | None = None
        self._uu_inv: NDArray[np.double] | None = None

        # Phonon bands included in integration of displacements.
        self._conditions_ii: NDArray[np.bool_] | None = None
        self._conditions_ij: NDArray[np.bool_] | None = None

        # Standard normals used by the last run, kept so that they can be
        # handed to another instance.
        self._random_normals: tuple[NDArray[np.double], NDArray[np.double]] | None = (
            None
        )

    def run(
        self,
        T: float,
        number_of_snapshots: int = 1,
        random_seed: int | None = None,
        first_snapshot: int = 0,
        random_normals: tuple[NDArray[np.double], NDArray[np.double]] | None = None,
        randn: tuple[NDArray[np.double], NDArray[np.double]] | None = None,
    ) -> None:
        """Calculate random displacements.

        Random displacements are calculated from eigensolutions stored by
        self._prepare() method.

        Parameters
        ----------
        T : float
            Temperature in Kelvin.
        number_of_snapshots : int, optional
            Number of snapshots to be generated. Default is 1.
        random_seed : int or None, optional
            Random seed. Each snapshot is drawn from its own generator,
            seeded by ``np.random.SeedSequence([random_seed, index])``, so
            that a snapshot depends on its index and not on how many
            snapshots are requested alongside it. Default is None, in which
            case the snapshots are drawn from unseeded generators and none
            of the guarantees below apply.
        first_snapshot : int, optional
            Index of the first snapshot to generate. Snapshots
            ``first_snapshot`` to ``first_snapshot + number_of_snapshots - 1``
            are returned. Default is 0. Only meaningful with ``random_seed``.
        random_normals : tuple of ndarray, optional
            The standard normals to turn into displacements, as returned by
            :meth:`generate_random_normals`. When given, ``random_seed``,
            ``first_snapshot`` and ``number_of_snapshots`` are ignored and the
            number of snapshots is taken from the arrays. Default is None,
            i.e. draw them. Giving another instance's normals puts both on the
            same realization of the randomness.
        randn : tuple, optional
            Deprecated alias of ``random_normals``.

        Notes
        -----
        With a seed, snapshot *i* is a function of ``random_seed`` and *i*
        alone. So asking for snapshots 0 to 99 and later for 100 to 199 gives
        the same 200 snapshots as asking for 0 to 199 at once, a large
        ensemble can be generated in blocks, and a single snapshot can be
        regenerated on its own.

        The displacements themselves are reproduced only to roundoff, since
        the summation order downstream of the random numbers depends on the
        array shapes and on the BLAS.

        NumPy does not promise that ``Generator`` distribution methods produce
        the same stream across its own versions (NEP 19), so a seed does not
        reproduce displacements across NumPy upgrades.

        """
        if randn is not None:
            warnings.warn(
                "RandomDisplacements.run(randn=...) is deprecated. Use "
                "random_normals=..., whose values are the same.",
                DeprecationWarning,
                stacklevel=2,
            )
            if random_normals is None:
                random_normals = randn

        if random_normals is None:
            random_normals = self.generate_random_normals(
                number_of_snapshots,
                random_seed=random_seed,
                first_snapshot=first_snapshot,
            )
        else:
            self._check_random_normals(random_normals)
        self._random_normals = random_normals
        randn_ii, randn_ij = random_normals
        number_of_snapshots = randn_ii.shape[1]

        N = len(self._comm_points)

        u_ii, self._conditions_ii = self._solve_ii(T, number_of_snapshots, randn_ii)
        if self._ij:
            u_ij, self._conditions_ij = self._solve_ij(T, number_of_snapshots, randn_ij)
        else:
            u_ij = 0
            self._conditions_ij = None

        mass = self._dynmat.supercell.masses.reshape(-1, 1)
        u = np.array((u_ii + u_ij) / np.sqrt(mass * N), dtype="double", order="C")
        if self._max_distance:
            dists = np.linalg.norm(u, axis=2)
            dists = np.repeat(dists, 3).reshape(dists.shape + (-1,))
            self._u = np.array(
                np.where(dists < self._max_distance, u, u / dists * self._max_distance),
                dtype="double",
                order="C",
            )
        else:
            self._u = u

    def generate_random_normals(
        self,
        number_of_snapshots: int = 1,
        random_seed: int | None = None,
        first_snapshot: int = 0,
    ) -> tuple[NDArray[np.double], NDArray[np.double]]:
        """Return standard normals for :meth:`run`.

        Drawing them separately from using them lets one realization be shared
        between structures; see the ``random_normals`` parameter of
        :meth:`run`.

        Parameters
        ----------
        number_of_snapshots : int, optional
            Number of snapshots to draw for. Default is 1.
        random_seed : int or None, optional
            Random seed. Snapshot *i* is drawn from its own generator, seeded
            by ``np.random.SeedSequence([random_seed, index])``, so it depends
            on its index and not on how many snapshots are drawn beside it.
            Default is None, i.e. unseeded.
        first_snapshot : int, optional
            Index of the first snapshot. Default is 0.

        Returns
        -------
        tuple[ndarray, ndarray]
            Shapes ``(n_ii, number_of_snapshots, n_band)`` and
            ``(n_ij, 2, number_of_snapshots, n_band)``, where ``n_ii`` counts
            the commensurate q with q = -q + G and ``n_ij`` the pairs of the
            rest. The two together hold ``3 * len(supercell)`` numbers per
            snapshot.

        """
        if random_seed is None or not np.issubdtype(type(random_seed), np.integer):
            n_ii, b_ii, n_ij, b_ij = self._normals_shape()
            rng = np.random.default_rng()
            n = number_of_snapshots
            return (
                rng.standard_normal(size=(n_ii, n, b_ii)),
                rng.standard_normal(size=(n_ij, 2, n, b_ij)),
            )
        return self._draw_seeded_normals(
            number_of_snapshots, random_seed, first_snapshot
        )

    def _draw_seeded_normals(
        self,
        number_of_snapshots: int,
        random_seed: int,
        first_snapshot: int = 0,
    ) -> tuple[NDArray[np.double], NDArray[np.double]]:
        """Draw standard normals with one generator per snapshot.

        Snapshot *i* comes from ``np.random.SeedSequence([random_seed, i])``,
        so it depends on its index and on nothing else. In one environment
        and with one seed, drawing n snapshots and drawing m > n therefore
        give the same first n.

        That is the point of the loop. It lets an ensemble be extended, be
        generated in blocks to bound memory, or have a single snapshot
        regenerated on its own, none of which disturbs the snapshots already
        drawn -- so displacements whose forces have been computed are not
        invalidated by wanting more of them.

        Drawing every snapshot from one generator would be simpler and would
        not have this property: the normals of a snapshot would sit at
        positions in the stream that depend on how many snapshots are drawn.

        The cost is building one generator per snapshot rather than one per
        call, which is Python object creation and not random number
        generation: about 16 us per snapshot, measured. That is a third of
        what :meth:`run` takes on an 80-atom supercell and under a tenth of it
        on a 128-atom one, and :meth:`run` is in turn small against computing
        forces for the snapshots it produces.

        """
        n_ii, b_ii, n_ij, b_ij = self._normals_shape()
        randn_ii: NDArray[np.double] = np.zeros(
            (n_ii, number_of_snapshots, b_ii), dtype="double"
        )
        randn_ij: NDArray[np.double] = np.zeros(
            (n_ij, 2, number_of_snapshots, b_ij), dtype="double"
        )
        for i in range(number_of_snapshots):
            rng = np.random.default_rng(
                np.random.SeedSequence([random_seed, first_snapshot + i])
            )
            randn_ii[:, i, :] = rng.standard_normal(size=(n_ii, b_ii))
            if n_ij:
                randn_ij[:, :, i, :] = rng.standard_normal(size=(n_ij, 2, b_ij))
        return randn_ii, randn_ij

    def _normals_shape(self) -> tuple[int, int, int, int]:
        """Return (n_ii, n_band, n_ij, n_band) of the standard normals."""
        n_ii = len(self._eigvals_ii)
        b_ii = len(self._eigvals_ii[0])
        n_ij = len(self._eigvals_ij) if self._ij else 0
        b_ij = len(self._eigvals_ij[0]) if self._ij else 0
        return n_ii, b_ii, n_ij, b_ij

    def _check_random_normals(
        self, random_normals: tuple[NDArray[np.double], NDArray[np.double]]
    ) -> None:
        """Raise if the given normals do not fit this instance.

        Normals shared from another structure fit only if that structure has
        the same supercell matrix and primitive cell.

        """
        if len(random_normals) != 2:
            raise ValueError("random_normals must be (randn_ii, randn_ij).")
        randn_ii, randn_ij = random_normals
        n_ii, b_ii, n_ij, b_ij = self._normals_shape()
        if randn_ii.ndim != 3 or randn_ii.shape[0] != n_ii or randn_ii.shape[2] != b_ii:
            raise ValueError(
                f"randn_ii has shape {randn_ii.shape}, expected "
                f"({n_ii}, number_of_snapshots, {b_ii})."
            )
        if not self._ij:
            return
        expected = (n_ij, 2, randn_ii.shape[1], b_ij)
        if tuple(randn_ij.shape) != expected:
            raise ValueError(
                f"randn_ij has shape {tuple(randn_ij.shape)}, expected {expected}."
            )

    @property
    def random_normals(
        self,
    ) -> tuple[NDArray[np.double], NDArray[np.double]] | None:
        """Return the standard normals the last :meth:`run` used.

        Pass these to another instance's :meth:`run` to give it the same
        realization of the randomness.

        """
        return self._random_normals

    @property
    def u(self) -> NDArray[np.double] | None:
        """Return random displacements."""
        return self._u

    @property
    def uu(self) -> NDArray[np.double] | None:
        """Return displacement-displacement correlation matrix."""
        return self._uu

    @property
    def uu_inv(self) -> NDArray[np.double] | None:
        """Return inversion of displacement-displacement correlation matrix."""
        return self._uu_inv

    @property
    def frequencies(self) -> NDArray[np.double]:
        """Setter and getter of phonon frequencies.

        Phonon frequencies themselves are not stored in this instance, but are
        stored in a way of eigenvalues. The eigenvalues can be stored via
        frequencies setter attributed.

        """
        if self._ij:
            eigvals = np.vstack((self._eigvals_ii, self._eigvals_ij))
        else:
            eigvals = np.array(self._eigvals_ii)
        freqs = np.sqrt(np.abs(eigvals)) * np.sign(eigvals) * self._factor
        return np.array(freqs, dtype="double", order="C")

    @frequencies.setter
    def frequencies(self, freqs: NDArray[np.double]) -> None:
        eigvals = (freqs / self._factor) ** 2 * np.sign(freqs)
        n_ii = len(self._eigvals_ii)
        n_ij = len(self._eigvals_ij) if self._ij else 0
        if len(eigvals) != n_ii + n_ij:
            raise RuntimeError("Dimension of frequencies is wrong.")
        self._eigvals_ii = eigvals[:n_ii]
        if self._ij:
            self._eigvals_ij = eigvals[n_ii:]

    @property
    def qpoints(self) -> NDArray[np.double]:
        """Return commensurate q-points where phonons are computed.."""
        N = len(self._comm_points)
        return self._comm_points[self._ii + self._ij] / float(N)

    @property
    def integrated_modes(self) -> NDArray[np.bool_]:
        """Return commensurate q-points where phonons are computed.."""
        if self._conditions_ii is None:
            raise RuntimeError("Run random displacements first.")

        if self._conditions_ij is None:
            return self._conditions_ii
        else:
            return np.vstack((self._conditions_ii, self._conditions_ij))

    @property
    def force_constants(self) -> NDArray[np.double] | None:
        """Return force constants."""
        return self._force_constants

    def run_d2f(self) -> None:
        """Calculate force constants from phonon eigen-solutions."""
        qpoints, eigvals, eigvecs = self._collect_eigensolutions()
        d2f = DynmatToForceConstants(
            self._dynmat.primitive,
            self._dynmat.supercell,
            use_openmp=self._dynmat.use_openmp,
        )
        d2f.commensurate_points = qpoints
        d2f.create_dynamical_matrices(eigvals, eigvecs)
        d2f.run()
        self._force_constants = d2f.force_constants

    def run_correlation_matrix(self, T: float) -> None:
        """Calculate displacement-displacement correlation matrix."""
        qpoints, eigvals, eigvecs = self._collect_eigensolutions()
        d2f = DynmatToForceConstants(
            self._dynmat.primitive,
            self._dynmat.supercell,
            use_openmp=self._dynmat.use_openmp,
        )
        masses = self._dynmat.supercell.masses
        d2f.commensurate_points = qpoints
        freqs = np.sqrt(np.abs(eigvals)) * self._factor
        conditions = freqs > self._cutoff_frequency
        a, _ = self._get_sigma(eigvals, T)
        a2 = a**2
        _a = np.where(conditions, a, 1)
        a2_inv = np.where(conditions, 1 / _a**2, 0)

        d2f.create_dynamical_matrices(a2_inv, eigvecs)
        d2f.run()
        self._uu_inv = np.array(d2f.force_constants, dtype="double", order="C")

        d2f.create_dynamical_matrices(a2, eigvecs)
        d2f.run()
        matrix = d2f.force_constants
        assert matrix is not None
        for i, m_i in enumerate(masses):
            for j, m_j in enumerate(masses):
                matrix[i, j] /= m_i * m_j
        self._uu = np.array(matrix, dtype="double", order="C")

    def treat_imaginary_modes(
        self, freq_from: float = 0.01, freq_to: float = 0.5, freq_shift: float = 1.0
    ) -> None:
        """Apply treatment to imaginary modes.

        This method modifies force constants to make phonon frequencies
        be real from imaginary. This treatment is expected to be finally
        forgotten after many iterations. Therefore it is unnecessary
        to be physical and can be physically dirty. If it works, it is OK,
        though good treatment may contribute to quick convergence.

        1) All frequencies at commensurate points are converted to their
        absolute values. freqs -> |freqs|.
        2) Phonon frequencies in the interval freq_from < |freqs| < freq_to
        are shifted by |freqs| + 1.

        """
        freqs = np.abs(self.frequencies)
        condition = np.logical_and(freqs > freq_from, freqs < freq_to)
        # self.frequencies is a setter attribute that sets eigenvalues.
        self.frequencies = np.where(condition, freqs + freq_shift, freqs)
        self.run_d2f()

    def _collect_eigensolutions(
        self,
    ) -> tuple[NDArray[np.double], NDArray[np.double], NDArray[np.cdouble]]:
        N = len(self._comm_points)

        qpoints = self._comm_points[self._ii] / float(N)
        eigvals = self._eigvals_ii
        eigvecs = []
        # Transform eigenvectors of D-type to those of C-type
        for q, eigvec in zip(qpoints, self._eigvecs_ii, strict=True):
            Vd = np.repeat(np.exp(-2j * np.pi * np.dot(self._ppos, q)), 3)
            eigvecs.append((Vd * eigvec.T).T)
        eigvecs = np.array(eigvecs, dtype="cdouble", order="C")

        if self._ij:
            eigvals = np.vstack((eigvals, self._eigvals_ij, self._eigvals_ij))
            eigvecs = np.vstack(
                (eigvecs, self._eigvecs_ij, self._eigvecs_ij), dtype="cdouble"
            )
            eigvecs[-len(self._ij) :] = eigvecs[-len(self._ij) :].conj()
            qpoints = self._comm_points[self._ii + self._ij * 2] / float(N)
            qpoints[-len(self._ij) :] = -qpoints[-len(self._ij) :]

        return qpoints, eigvals, eigvecs

    def _prepare(self) -> None:
        """Calculate eigensolutions and phase factors used for random disps.

        A is a set of q-points where q = -q + G. B is a set of other q-points
        than A.

        D-type dynamical matrix is used for A to describe displacements by only
        real values, i.e., eigenvectors and phase factors.
        However C-type dynamical matrix is used for B in this implementation.

        """
        supercell = self._dynmat.supercell
        primitive = self._dynmat.primitive
        # Scaled positions in the primitive basis, ordered (primitive atom,
        # lattice point); lpos drops the basis position and leaves the lattice
        # vector.
        tmat = np.dot(supercell.cell, np.linalg.inv(primitive.cell))
        spos = np.dot(supercell.scaled_positions, tmat)[self._ppl2s].reshape(
            self._n_patom, self._n_lattice, 3
        )
        lpos = spos - primitive.scaled_positions[:, None, :]

        N = len(self._comm_points)
        eigvals_ii = []
        eigvecs_ii = []
        phase_ii = []

        # q in A
        for q in self._comm_points[self._ii] / float(N):
            self._dynmat.run(q)
            dynmat = self._dynmat.dynamical_matrix
            assert dynmat is not None
            dm = self._C_to_D(dynmat, q)
            eigvals, eigvecs = np.linalg.eigh(dm)  # dm is real.
            eigvals_ii.append(eigvals)
            eigvecs_ii.append(eigvecs)
            phase_ii.append(np.cos(2 * np.pi * np.dot(lpos, q)))
        self._eigvals_ii = np.array(eigvals_ii, dtype="double", order="C")
        self._eigvecs_ii = np.array(eigvecs_ii, dtype="double", order="C")
        self._phase_ii = np.array(phase_ii, dtype="double", order="C")

        # q in B
        if self._ij:
            eigvals_ij = []
            eigvecs_ij = []
            phase_ij = []
            for q in self._comm_points[self._ij] / float(N):
                self._dynmat.run(q)
                dm_complex = self._dynmat.dynamical_matrix
                assert dm_complex is not None
                eigvals, eigvecs = np.linalg.eigh(dm_complex)
                eigvals_ij.append(eigvals.real)  # type: ignore
                eigvecs_ij.append(eigvecs)
                phase_ij.append(np.exp(2j * np.pi * np.dot(spos, q)))
            self._eigvals_ij = np.array(eigvals_ij, dtype="double", order="C")
            self._eigvecs_ij = np.array(eigvecs_ij, dtype="cdouble", order="C")
            self._phase_ij = np.array(phase_ij, dtype="cdouble", order="C")

    def _C_to_D(
        self, dm: NDArray[np.cdouble], q: NDArray[np.double]
    ) -> NDArray[np.double]:
        """Transform C-type dynamical matrix to D-type."""
        V = np.repeat(np.exp(2j * np.pi * np.dot(self._ppos, q)), 3)
        dm_D = (V * (V.conj() * dm).T).T
        dm_real: NDArray[np.double] = dm_D.real  # C-type to D-type
        assert np.abs((dm_D - dm_real)).max() < 1e-8

        return dm_real

    def _setup_sampling_qpoints(
        self, slat: NDArray[np.double], plat: NDArray[np.double]
    ) -> None:
        smat = np.rint(np.dot(slat, np.linalg.inv(plat)).T).astype(int)
        self._comm_points = get_commensurate_points_in_integers(smat)
        self._ii, self._ij = categorize_commensurate_points(self._comm_points)

    def _amplitudes(
        self,
        norm_dist: NDArray[np.double],
        sigma: NDArray[np.double],
        eigvecs: NDArray,
    ) -> NDArray:
        """Return the mode amplitudes of one commensurate q point.

        'symmetric' projects the normals onto the eigenvectors before scaling
        them, so that the pair of contractions with eigvecs makes
        E.diag(sigma).E^dagger. That product is unchanged by a rotation within
        a degenerate subspace or a phase per band, which is what makes the
        displacements independent of the eigenvectors the solver returned.

        """
        if self._sampling_matrix == "symmetric":
            return np.dot(norm_dist, eigvecs.conj()) * sigma
        return norm_dist * sigma

    def _solve_ii(self, T: float, number_of_snapshots: int, randn: NDArray[np.double]):
        """Solve ii terms.

        randn parameter is used for the test.

        """
        u = np.zeros(
            (number_of_snapshots, self._n_patom, 3, self._n_lattice),
            dtype="double",
        )

        sigmas, conditions = self._get_sigma(self._eigvals_ii, T)
        for norm_dist, sigma, eigvecs, phase in zip(
            randn, sigmas, self._eigvecs_ii, self._phase_ii, strict=True
        ):
            amplitudes = self._amplitudes(norm_dist, sigma, eigvecs)
            u_red = np.dot(amplitudes, eigvecs.T).reshape(
                number_of_snapshots, self._n_patom, 3
            )
            # u_red.shape = (snapshots, patoms, 3)
            # phase.shape = (patoms, lattice points)
            u += u_red[:, :, :, None] * phase[None, :, None, :]

        return self._to_supercell(u), conditions

    def _solve_ij(
        self,
        T: float,
        number_of_snapshots: int,
        randn: NDArray[np.double],
    ):
        """Solve ij terms.

        randn parameter is used for the test.

        """
        u = np.zeros(
            (number_of_snapshots, self._n_patom, 3, self._n_lattice),
            dtype="double",
        )
        sigmas, conditions = self._get_sigma(self._eigvals_ij, T)
        for norm_dist, sigma, eigvecs, phase in zip(
            randn, sigmas, self._eigvecs_ij, self._phase_ij, strict=True
        ):
            # The two sets of normals are the real and imaginary parts of one
            # complex normal. Projecting them separately and recombining below
            # is the same as projecting the complex vector, because the
            # projection is complex linear and Re[(a + ib) p] = Re[a p] -
            # Im[b p]. E^dagger is unitary, so the projected amplitudes are
            # again complex normal with the same second moments.
            amplitudes = self._amplitudes(norm_dist, sigma, eigvecs)
            u_red = np.dot(amplitudes, eigvecs.T).reshape(
                2, number_of_snapshots, self._n_patom, 3
            )
            # u_red.shape = (2, snapshots, patoms, 3)
            # phase.shape = (patoms, lattice points)
            ph = phase[None, :, None, :]
            u += (u_red[0][:, :, :, None] * ph).real
            u -= (u_red[1][:, :, :, None] * ph).imag

        return self._to_supercell(u) * np.sqrt(2), conditions

    def _to_supercell(self, u: NDArray[np.double]) -> NDArray[np.double]:
        """Return (snapshots, patoms, 3, lattice) as (snapshots, satoms, 3).

        The lattice point is the innermost axis while the contributions are
        accumulated, because that is the axis the phase runs along.

        """
        n = u.shape[0]
        flat = u.transpose(0, 1, 3, 2).reshape(n, self._n_patom * self._n_lattice, 3)
        return np.array(flat[:, self._s2ppl, :], dtype="double", order="C")

    def _get_sigma(
        self, eigvals: NDArray[np.double], T: float
    ) -> tuple[NDArray[np.double], NDArray[np.bool_]]:
        """Return sigma in sqrt(AMU).Angstrom unit."""
        freqs = np.sqrt(np.abs(eigvals)) * self._factor
        conditions = freqs > self._cutoff_frequency
        freqs = np.where(conditions, freqs, 1)
        if self._dist_func == "classical":
            sigma = np.sqrt(T * self._unit_conversion_classical) / freqs
        else:
            n = bose_einstein_dist(freqs, T)
            sigma = np.sqrt(self._unit_conversion / freqs * (0.5 + n))
        sigma = np.where(conditions, sigma, 0)
        return sigma, conditions
