package:
  name: phonopy
  version: version_from_shell

source:
  git_url: https://github.com/phonopy/phonopy.git
  git_branch: {{ environ.get('GIT_BRANCH', 'master') }}

build:
  script_env:
    - GIT_BRANCH

  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - elastic = elastic:main
    #
    # Would create an entry point called elastic that calls elastic.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - pip
    - numpy>=1.11
    - matplotlib-base>=2.0.0
    - pyyaml
    - h5py
    - spglib
    - scipy

  run:
    - python
    - pip
    - numpy>=1.11
    - matplotlib-base>=2.0.0
    - pyyaml
    - h5py
    - spglib
    - scipy

test:
  # Python imports
  imports:
    - phonopy

#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - cd example/MgO
#    - phonopy -f vasprun.xml-001 vasprun.xml-002
#    - phonopy -p band.conf
#    - phonopy -p --nac band.conf

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://phonopy.github.io/phonopy/
  license: BSD
  summary: 'Phonon calculation with finite displacements method.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
