#!/usr/bin/env python

# Copyright (C) 2011 Atsushi Togo
# All rights reserved.
#
# This file is part of phonopy.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# * Neither the name of the phonopy project nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import sys
import numpy as np

try:
    import yaml
except ImportError:
    print "You need to install python-yaml."
    exit(1)
    
try:
    from yaml import CLoader as Loader
    from yaml import CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper

from phonopy.units import VaspToTHz



def get_plot_data(data, segment_scales=None):
    segment_positions = []
    frequencies = []
    distances = []
    npoints = data['nqpoint'] / data['npath']
    distance_scale = 1.0
    distance = 0.0
    prev_distance = 0.0

    for j, v in enumerate(data['phonon']):
        if j % npoints == 0:
            segment_positions.append(distance)
            if segment_scales is not None:
                distance_scale = segment_scales[len(segment_positions) - 1]

        frequencies.append([f['frequency'] for f in v['band']])
        delta = v['distance'] - prev_distance
        distance += delta * distance_scale
        distances.append(distance)
        prev_distance = v['distance']

        print j, distance_scale, distance, v['distance']

    return distances, frequencies, segment_positions



# Parse options
from optparse import OptionParser
parser = OptionParser()
parser.set_defaults(band_labels=None,
                    factor=1.0,
                    f_max=None, 
                    f_min=None,
                    is_gnuplot=False,
                    is_points=False,
                    is_vertial_line=False,
                    output_filename=None,
                    segment_scales=None,
                    xlabel=None,
                    ylabel=None,
                    show_legend=False,
                    title=None)
parser.add_option("--band_labels", dest="band_labels", action="store", type="string",
                  help="Show labels at band segments")
parser.add_option("--factor", dest="factor", type="float",
    		help="Conversion factor to favorite frequency unit")
parser.add_option("--fmax", dest="f_max", type="float",
                  help="Maximum frequency plotted")
parser.add_option("--fmin", dest="f_min", type="float",
                  help="Minimum frequency plotted")
parser.add_option("--gnuplot", dest="is_gnuplot", action="store_true",
                  help="Output in gnuplot data style")
parser.add_option("--legend", dest="show_legend",
                  action="store_true",
                  help="Show legend")
parser.add_option("--line", "-l", dest="is_vertial_line",
                  action="store_true",
                  help="Vertial line is drawn at between paths")
parser.add_option("-o", "--output", dest="output_filename",
                  action="store", type="string",
                  help="Output filename of PDF plot")
parser.add_option("--segment_scales", dest="segment_scales",
                  action="store", type="string",
                  help="Scale band segments")
parser.add_option("--xlabel", dest="xlabel", action="store", type="string",
                  help="Specify x-label")
parser.add_option("--ylabel", dest="ylabel", action="store", type="string",
                  help="Specify y-label")
parser.add_option("--points", dest="is_points",
                  action="store_true",
                  help="Draw points")
parser.add_option("-t", "--title", dest="title", action="store",
                  type="string", help="Title of plot")
(options, args) = parser.parse_args()

if options.output_filename:
    import matplotlib
    matplotlib.use('Agg')            

if not options.is_gnuplot:
    import matplotlib.pyplot as plt
    if options.band_labels:
        
        from matplotlib import rc
        rc('text', usetex=True)

colors = ['b-', 'g-', 'r-', 'c-', 'm-', 'y-', 'k-', 'b--', 'g--', 'r--', 'c--', 'm--', 'y--', 'k--']
if options.is_points:
    colors = [x + 'o' for x in colors]

count = 0


if len(args) == 0:
    filenames = ['band.yaml']
else:
    filenames = args

if options.is_gnuplot:
    print "# distance  frequency (bands are separated by blank lines)"

if options.segment_scales:
    segment_scales = [float(x) for x in options.segment_scales.split()]
else:
    segment_scales = None


for i, filename in enumerate(filenames):
    string = open(filename).read()
    data = yaml.load(string, Loader=Loader)
    (distances,
     frequencies,
     segment_positions) = get_plot_data(data, segment_scales=segment_scales)

    if options.is_gnuplot:
        print "# segments:",
        for v in segment_positions:
            print "%10.8f" % v,
        print "%10.8f" % distances[-1]
        
    elif options.is_vertial_line and len(filenames) == 1:
        for v in segment_positions[1:]:
            plt.axvline(x=v, linewidth=0.5, color='b')

    for j, freqs in enumerate(np.array(frequencies).T):
        if options.is_gnuplot:
            for d, f in zip(distances, freqs * options.factor):
                print d,f
            print
        else:
            if j == 0:
                plt.plot(distances, freqs * options.factor, colors[i],
                         label=filename)
            else:
                plt.plot(distances, freqs * options.factor, colors[i])

    if options.is_gnuplot:
        print

    
if not options.is_gnuplot:
    if options.xlabel is None:
        plt.xlabel('Wave vector')
    else:
        plt.xlabel(options.xlabel)
    if options.ylabel is None:
        plt.ylabel('Frequency')
    else:
        plt.ylabel(options.ylabel)
    
    plt.xlim(distances[0], distances[-1])
    if options.f_max is not None:
        plt.ylim(ymax = options.f_max)
    if options.f_min is not None:
        plt.ylim(ymin = options.f_min)
    plt.axhline(y=0, linestyle=':', linewidth=0.5, color='b')
    if len(filenames) == 1:
        xticks = segment_positions + [distances[-1]]
        if options.band_labels:
            band_labels = [x for x in options.band_labels.split()]
            if len(band_labels) == len(xticks):
                plt.xticks(xticks, band_labels)
            else:
                print "Numbers of labels and band segments don't match."
                sys.exit(1)
        else:
            plt.xticks(xticks, [''] * len(xticks))
    else:
        plt.xticks([])
    
    if options.title is not None:
        plt.title(options.title)

    if options.show_legend:
        plt.legend()
    
    if options.output_filename is not None:
        plt.rcParams['pdf.fonttype'] = 42
        plt.rcParams['font.family'] = 'serif'
        plt.savefig(options.output_filename)
    else:
        plt.show()
    

