name: phonopy test on windows and macos

on:
  pull_request:
    branches: [develop]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      # Use conda-incubator/setup-miniconda for precise control of conda infrastructure
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-activate-base: false
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependent packages
        run: |
          conda activate test
          conda install --yes python=${{ matrix.python-version }}
          conda install --yes matplotlib-base pyyaml h5py numpy scipy pytest spglib cmake c-compiler cxx-compiler maturin
      - name: Install symfc develop branch
        run: |
          conda activate test
          git clone https://github.com/symfc/symfc.git
          cd symfc
          pip install -e . -vvv
      - name: Build and install phonors
        run: |
          conda activate test
          git clone https://github.com/phonopy/phonors.git
          cd phonors
          maturin develop --release
      - name: Setup phonopy
        run: |
          conda activate test
          pip install -e . -v
      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v test

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-activate-base: false
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda activate test
          conda install --yes -c conda-forge python=${{ matrix.python-version }}
          conda install --yes -c conda-forge matplotlib-base pyyaml scipy numpy spglib h5py pip pytest codecov pytest-cov c-compiler cxx-compiler cmake pypolymlp ase maturin
      - name: Setup symfc
        run: |
          conda activate test
          git clone https://github.com/symfc/symfc.git
          cd symfc
          pip install -e . -vvv
          cd ..
      - name: Build and install phonors
        run: |
          conda activate test
          git clone https://github.com/phonopy/phonors.git
          cd phonors
          maturin develop --release
      - name: Setup phonopy
        run: |
          conda activate test
          pip install -e . -vvv
      - name: Test with pytest
        run: |
          conda activate test
          pytest -v test
